<a href="https://colab.research.google.com/github/sanjayyadav2892005-spec/Iris.model/blob/main/iris_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [73]:
import pandas as pd

In [74]:
data=pd.read_csv('/content/Iris.csv')

In [75]:
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [76]:
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [77]:
data["Species"].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [78]:
x=data.drop(columns=["Id","Species"])

In [79]:
from sklearn.model_selection import train_test_split

In [80]:
model = LogisticRegression()

In [81]:
model.fit(x_train,y_train)

LogisticRegression()

In [82]:
x_train,x_test,y_train,y_test=train_test_split(x,data['Species'],test_size=0.2,random_state=42)

In [83]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [84]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

In [85]:
y_pred=model.fit(x_train,y_train).predict(x_test)

In [86]:
acc=accuracy_score(y_test,y_pred)

In [87]:
print(f"accuracy_score : {acc}")

accuracy_score : 1.0

In [94]:
import joblib

In [93]:
joblib.dump(model,"iris_model.pkl")

['iris_model.pkl']

In [ ]:
prec=precision_score(y_test,y_pred,average='weighted')